2 5 10 20 50 100 200 500 1000
2, 2
Traceback (most recent call last):
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'formatters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cndd2/fangming/projects/SCF_package/SingleCellFusion/scripts/SCF_main_repeat_subsampling.py", line 4, in <module>
    from __init__ import *
  File "/cndd2/fangming/projects/SCF_package/v2_dev/SingleCellFusion/scripts/__init__.py", line 29, in <module>
    set_matplotlib_formats('retina')
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/IPython/core/display.py", line 1501, in set_matplotlib_formats
    select_figure_formats(shell, formats, **kw)
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/IPython/core/pylabtools.py", line 224, in select_figure_formats
    svg_formatter = shell.display_formatter.formatters['image/svg+xml']
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/IPython/core/formatters.py", line 85, in _formatters_default
    f = cls(parent=self)
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/config/configurable.py", line 84, in __init__
    self.config = config
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 574, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 1134, in _notify_trait
    self.notify_change(Bunch(
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 1176, in notify_change
    c(change)
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 819, in compatible_observer
    return func(self, change)
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/config/configurable.py", line 180, in _config_changed
    traits = self.traits(config=True)
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 1421, in traits
    traits = dict([memb for memb in getmembers(self.__class__) if
  File "/cndd2/fangming/venvs/routine/lib/python3.8/site-packages/traitlets/traitlets.py", line 232, in getmembers
    for key in dir(object):
KeyboardInterrupt
Command terminated by signal 2
1.53user 0.19system 0:03.13elapsed 55%CPU (0avgtext+0avgdata 144356maxresident)k
736inputs+136outputs (0major+35274minor)pagefaults 0swaps
